language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing"

before_script:
  - echo "no test"

script:
  - docker build -t simple-node .
  - docker tag simple-node leok13/simple-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push leok13/simple-node
